#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker



# Ubuntu + Debian
- name: Install Docker on Ubuntu/Debian
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when:
    - ansible_facts['os_family'] == "Debian"

# Amazon Linux
- name: Install Docker on Amazon Linux
  yum:
    name: docker
    state: present
  when:
    - ansible_facts['distribution'] == "Amazon"

# Start Docker Service
- name: Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes