# ================================
# Inventory Group: Servers
# ================================
[servers]

# Worker Node 1 IP Address
worker-node-1 ansible_host=3.109.217.232

# Worker Node 2 IP Address
worker-node-2 ansible_host=13.201.16.244


# ================================
# SSH User Configuration
# ================================

# SSH Username for Worker Node 1
worker-node-1 ansible_user=ubuntu

# SSH Username for Worker Node 2
worker-node-2 ansible_user=ubuntu


# ================================
# Global Variables for All Servers
# ================================
[all:vars]

# Private SSH Key Path
ansible_ssh_private_key_file=/home/ubuntu/.ssh/ansible-master

# Python Interpreter Path
ansible_python_interpreter=/usr/bin/python3

# Disable SSH host key verification prompt
ansible_host_key_checking=false