apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-ns

spec:
  type: ClusterIP
  selector:
    app: apache-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80