apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app-ns

spec:
  type: ClusterIP
  selector:
    app: node-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80