apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "myapp.fullname" . }}-pre-install'
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install
          image: busybox
          command:
            - sh
            - -c
            - 'echo "Pre-install hook executed successfully"'