kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  # Control Plane Node
  - role: control-plane

    # Map EC2 host port -> kind node port
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP

  # Worker Node 1
  - role: worker

  # Worker Node 2
  - role: worker

  # Worker Node 3
  - role: worker