# Create Secret
apiVersion: v1
kind: Secret

metadata:
  name: my-app-secrets                 # Name of the Secret object

type: Opaque                           # Generic secret type for custom sensitive data

data:
  DB_USERNAME: YWRtaW4=                # Base64 encoded value of "admin"
  DB_PASSWORD: cGFzc3dvcmQ=            # Base64 encoded value of "password"
  VULCAN_TOKEN: YnNjYmh1ZmhqaWY9       # Base64 encoded API/Auth token

---

# Create Pod
apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod                      # Pod name

spec:
  containers:
  - name: nginx-container              # Container name
    image: nginx:latest                # Nginx container image

    ports:
    - containerPort: 80                # Expose port 80 inside the container

    env:                               # Inject Secret values as environment variables

    # Read DB_USERNAME from Secret
    - name: DB_USERNAME                # Environment variable inside container
      valueFrom:
        secretKeyRef:
          name: my-app-secrets         # Secret object name
          key: DB_USERNAME             # Specific key inside Secret

    # Read DB_PASSWORD from Secret
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app-secrets
          key: DB_PASSWORD

    # Read VULCAN_TOKEN from Secret
    - name: VULCAN_TOKEN
      valueFrom:
        secretKeyRef:
          name: my-app-secrets
          key: VULCAN_TOKEN